### PR TITLE
Introduce maven-wrapper

### PR DESCRIPTION
**Pull request by gwenneg**
Same PR as https://github.com/RedHatInsights/notifications-backend/pull/126 for the same reasons.

### CODE REVIEW

**Review by josejulio — APPROVED** [review]
lgtm

**Review by josejulio — CHANGES_REQUESTED** [review]
Could you update the README to point this usage of the wrapper?

**Comment by gwenneg** [comment]
README updated

**Review by josejulio — APPROVED** [review]
lgtm

**Comment by gwenneg** [comment]
Thanks!

**Pull request merged**
