### PR TITLE
fix: logging percents to cloudwatch

### PR DESCRIPTION
**Pull request by vkrizan**
https://github.com/quarkiverse/quarkus-logging-cloudwatch/issues/457

RHINENG-774

### CODE REVIEW

**Comment by vkrizan** [comment]
@gwenneg @josejulio can you please help with the following error?
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.13.3.Final:build (default) on project app: Execution default of goal io.quarkus:quarkus-maven-plugin:2.13.3.Final:build failed: A required class was missing while executing io.quarkus:quarkus-maven-plugin:2.13.3.Final:build: jakarta/enterprise/inject/spi/DeploymentException
```

Could it be the Quarkus platform version mismatch? If so, how can we still upgrade cloudwatch package?

Thank you.

**Comment by gwenneg** [comment]
I think you'll need to bump Quarkus to 3.x in this project if you want to use the latest quarkus-logging-cloudwatch releases.

Quarkus 2.x relied on `javax.` packages which were "recently" replaced with `jakarta.` packages in Quarkus 3 (that one of the major breaking changes of Quarkus 3) and the error message looks related to that.

**Comment by vkrizan** [comment]
@gwenneg we are planning to do that. Is there a way to overcome it? Maybe backporting the fix to version 5 of cloudwatch logging?

**Comment by vkrizan** [comment]
Superseded by #602

**Pull request closed without merging**
